### ISSUE TITLE
Images are blank

### ISSUE THREAD

**Issue by jradavenport** [austin-boeck/spot_flicker#1]
Looks like the `plt.savefig()` command got put in the wrong place. Might want to change it to be like this:

``` python
...
plt.savefig('filename.png', dpi=300)
plt.show()
```

If you want to save the figure directly without _seeing_ it:

``` python
...
plt.savefig('filename.png', dpi=300)
plt.close()
```

I also like to explicitly give the extension (because `savefig` can save as a .pdf, .png, etc), and I like to increase the default resolution w/ the DPI.

**Comment by austin-boeck** [comment]
I've moved where the plt.savefig() command lies within the plot block, and images are no longer blank. Resolution has also been specified at 300 DPI.
