### ISSUE TITLE
Highlighting flares

### ISSUE THREAD

**Issue by jradavenport** [austin-boeck/spot_flicker#2]
I see 2 issues in your code that will be easy to fix:
1. when you read the flare start/stop times, you read them in as a 2xN array, rather than 2 1xN arrays explicitly. I would change this to be more like:

``` python
starttime, stoptime = np.loadtxt(file2, usecols=(5,6), unpack=True)
```

2.highlightin the flares: this was a tougher problem, so keep working at it. You need to find the data within the light curve _where_ the flare exists. If all you have is the start and stop time for every flare, you want to find where each of these exists. Here's some code towards a brute-force solution, based on what FBEYE does:

``` python
...
starttime, stoptime = np.loadtxt(file2, usecols=(5,6), unpack=True)

plt.figure()
plt.plot(time, flux, 'b') # plot the original data in blue

# now lets loop over every flare, find the data that falls within the start/stop times
for k in range(0, len(starttime)):
    # this finds WHERE the logic statements are true for the k'th given flare
    x = np.where((time >= starttime[k]) & (time <= stoptime[k])

    # now let's plot that flare
    plt.scatter(time[x], flux[x], c='red')

plt.show()
```

**Comment by austin-boeck** [comment]
A bug has been fixed where the wrong data was read in for start and stop times. I have also added the above block of code containing the _for_ loop to actually go about highlighting the flares. The flares are now successfully highlighted.

Very faint orange lines were also added to the plots aligned with peak times of flares, to further aid in readability.
