### ISSUE TITLE
Delete the flares!

### ISSUE THREAD

**Issue by jradavenport** [austin-boeck/spot_flicker#4]
make new arrays for `time, flux, error` that do not have any known flares

**Comment by austin-boeck** [comment]
Flares have been removed and the resultant code has been pushed. Now on to smoothing! (Also, my computer decided to unbrick itself, which is nice)

**Comment by jradavenport** [comment]
sweet! push latest results to the repo? can't see them yet

**Comment by jradavenport** [comment]
I should amend that statement: your update is not in the _master_ branch. that's OK, but you might want to merge them
